//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSAccounting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string _Exit {
            get {
                return ResourceManager.GetString("_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile.
        /// </summary>
        public static string _Profile {
            get {
                return ResourceManager.GetString("_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed To Delete This Account!.
        /// </summary>
        public static string AccDelNotAllowed {
            get {
                return ResourceManager.GetString("AccDelNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Close.
        /// </summary>
        public static string AccountClose {
            get {
                return ResourceManager.GetString("AccountClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If there is Invoices, journals, Receipts, or Clients connect to this Account you will must delete them frist...
        /// </summary>
        public static string AccountDelNote {
            get {
                return ResourceManager.GetString("AccountDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: only allowed to close the accounts in the end of the year.
        /// </summary>
        public static string AccountsCloseNote {
            get {
                return ResourceManager.GetString("AccountsCloseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Tree.
        /// </summary>
        public static string AccountsTree {
            get {
                return ResourceManager.GetString("AccountsTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transactions.
        /// </summary>
        public static string AccountTransactions {
            get {
                return ResourceManager.GetString("AccountTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Least One Invoice Line!.
        /// </summary>
        public static string AddInvoiceLines {
            get {
                return ResourceManager.GetString("AddInvoiceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Account.
        /// </summary>
        public static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Client.
        /// </summary>
        public static string AddNewClient {
            get {
                return ResourceManager.GetString("AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Invoice.
        /// </summary>
        public static string AddNewInvoice {
            get {
                return ResourceManager.GetString("AddNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Journal.
        /// </summary>
        public static string AddNewJournal {
            get {
                return ResourceManager.GetString("AddNewJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        public static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Receitpt.
        /// </summary>
        public static string AddNewReceitpt {
            get {
                return ResourceManager.GetString("AddNewReceitpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        public static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Store.
        /// </summary>
        public static string AddNewStore {
            get {
                return ResourceManager.GetString("AddNewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address *.
        /// </summary>
        public static string AddressReq {
            get {
                return ResourceManager.GetString("AddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Du(USD).
        /// </summary>
        public static string AmountDu {
            get {
                return ResourceManager.GetString("AmountDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount *.
        /// </summary>
        public static string AmountReq {
            get {
                return ResourceManager.GetString("AmountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assests.
        /// </summary>
        public static string Assests {
            get {
                return ResourceManager.GetString("Assests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assests Total.
        /// </summary>
        public static string AssestsTotal {
            get {
                return ResourceManager.GetString("AssestsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Least One Journal!.
        /// </summary>
        public static string AtLeastOneJournal {
            get {
                return ResourceManager.GetString("AtLeastOneJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Now.
        /// </summary>
        public static string BackupNow {
            get {
                return ResourceManager.GetString("BackupNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Setting.
        /// </summary>
        public static string BackupSetting {
            get {
                return ResourceManager.GetString("BackupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Time.
        /// </summary>
        public static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank*.
        /// </summary>
        public static string BankReq {
            get {
                return ResourceManager.GetString("BankReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Num &lt; 999999999.
        /// </summary>
        public static string BigNum {
            get {
                return ResourceManager.GetString("BigNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed To.
        /// </summary>
        public static string BilledTo {
            get {
                return ResourceManager.GetString("BilledTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills Due Soon.
        /// </summary>
        public static string BillsDueSoon {
            get {
                return ResourceManager.GetString("BillsDueSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloked.
        /// </summary>
        public static string Bloked {
            get {
                return ResourceManager.GetString("Bloked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Safe.
        /// </summary>
        public static string BoxSafe {
            get {
                return ResourceManager.GetString("BoxSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Operation.
        /// </summary>
        public static string CashOperation {
            get {
                return ResourceManager.GetString("CashOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch.
        /// </summary>
        public static string Catch {
            get {
                return ResourceManager.GetString("Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch Receipt.
        /// </summary>
        public static string CatchReceipt {
            get {
                return ResourceManager.GetString("CatchReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatchReceipts.
        /// </summary>
        public static string CatchReceipts {
            get {
                return ResourceManager.GetString("CatchReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catchs.
        /// </summary>
        public static string Catchs {
            get {
                return ResourceManager.GetString("Catchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If there is Products with this Category you will must delete them frist...
        /// </summary>
        public static string CategoryDelNote {
            get {
                return ResourceManager.GetString("CategoryDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City *.
        /// </summary>
        public static string CityReq {
            get {
                return ResourceManager.GetString("CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Chose A Client!.
        /// </summary>
        public static string ClienNotChosenError {
            get {
                return ResourceManager.GetString("ClienNotChosenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If there is Invoices, journals, Receipts connect to this Client you will must delete them frist...
        /// </summary>
        public static string ClientDelNote {
            get {
                return ResourceManager.GetString("ClientDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Num, Name.
        /// </summary>
        public static string ClientNumName {
            get {
                return ResourceManager.GetString("ClientNumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is exist!!.
        /// </summary>
        public static string CodeExist {
            get {
                return ResourceManager.GetString("CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code *.
        /// </summary>
        public static string CodeReq {
            get {
                return ResourceManager.GetString("CodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm User Status.
        /// </summary>
        public static string ConfirmUserStatus {
            get {
                return ResourceManager.GetString("ConfirmUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorpInfo.
        /// </summary>
        public static string CorpInfo {
            get {
                return ResourceManager.GetString("CorpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corperation Info Not Found.
        /// </summary>
        public static string CorpNotFound {
            get {
                return ResourceManager.GetString("CorpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Goods Sold.
        /// </summary>
        public static string CostofGoodsSold {
            get {
                return ResourceManager.GetString("CostofGoodsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Balance.
        /// </summary>
        public static string CreditBalance {
            get {
                return ResourceManager.GetString("CreditBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Clients.
        /// </summary>
        public static string CreditClients {
            get {
                return ResourceManager.GetString("CreditClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit is not eqaul Debt.
        /// </summary>
        public static string CreditDebtNotEqaul {
            get {
                return ResourceManager.GetString("CreditDebtNotEqaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit And Debt 0.
        /// </summary>
        public static string CreditDebtZero {
            get {
                return ResourceManager.GetString("CreditDebtZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Total.
        /// </summary>
        public static string CreditTotal {
            get {
                return ResourceManager.GetString("CreditTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Invoice.
        /// </summary>
        public static string DateOfInvoice {
            get {
                return ResourceManager.GetString("DateOfInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Receipt.
        /// </summary>
        public static string DateOfReceipt {
            get {
                return ResourceManager.GetString("DateOfReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date *.
        /// </summary>
        public static string DateReq {
            get {
                return ResourceManager.GetString("DateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebtBalance.
        /// </summary>
        public static string DebtBalance {
            get {
                return ResourceManager.GetString("DebtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Clients.
        /// </summary>
        public static string DebtClients {
            get {
                return ResourceManager.GetString("DebtClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Total.
        /// </summary>
        public static string DebtTotal {
            get {
                return ResourceManager.GetString("DebtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete.
        /// </summary>
        public static string DeleteConfirmMsg {
            get {
                return ResourceManager.GetString("DeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have permetion to Delete.
        /// </summary>
        public static string DeleteUnAuth {
            get {
                return ResourceManager.GetString("DeleteUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details *.
        /// </summary>
        public static string DetailsReq {
            get {
                return ResourceManager.GetString("DetailsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount%.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Permitted.
        /// </summary>
        public static string DiscountPermitted {
            get {
                return ResourceManager.GetString("DiscountPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        public static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        public static string Drawings {
            get {
                return ResourceManager.GetString("Drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Units!!.
        /// </summary>
        public static string DuplicateUnits {
            get {
                return ResourceManager.GetString("DuplicateUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Journal.
        /// </summary>
        public static string EditJournal {
            get {
                return ResourceManager.GetString("EditJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Store.
        /// </summary>
        public static string EditStore {
            get {
                return ResourceManager.GetString("EditStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Not Valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year Not Closed.
        /// </summary>
        public static string ErrorLastYearNotClosed {
            get {
                return ResourceManager.GetString("ErrorLastYearNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Already Closed.
        /// </summary>
        public static string ErrorYearAlreadyClosed {
            get {
                return ResourceManager.GetString("ErrorYearAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild Message!!.
        /// </summary>
        public static string FaildMsg {
            get {
                return ResourceManager.GetString("FaildMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild Process!!.
        /// </summary>
        public static string FaildProcess {
            get {
                return ResourceManager.GetString("FaildProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the last fiscal year are being closed.
        /// </summary>
        public static string FiscalYearBeingClosed {
            get {
                return ResourceManager.GetString("FiscalYearBeingClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring accounts to the new fiscal year.
        /// </summary>
        public static string FiscalYearBeingTrans {
            get {
                return ResourceManager.GetString("FiscalYearBeingTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Of Fiscal Year.
        /// </summary>
        public static string FiscalYearClose {
            get {
                return ResourceManager.GetString("FiscalYearClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frist Name.
        /// </summary>
        public static string FristName {
            get {
                return ResourceManager.GetString("FristName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FristName *.
        /// </summary>
        public static string FristNameReq {
            get {
                return ResourceManager.GetString("FristNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fromِ Account.
        /// </summary>
        public static string FromAccount {
            get {
                return ResourceManager.GetString("FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Client.
        /// </summary>
        public static string FromClient {
            get {
                return ResourceManager.GetString("FromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Water Electricity.
        /// </summary>
        public static string GasWaterElectricity {
            get {
                return ResourceManager.GetString("GasWaterElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income And Expenses.
        /// </summary>
        public static string IncomeAndExpenses {
            get {
                return ResourceManager.GetString("IncomeAndExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statment - Profit/loss.
        /// </summary>
        public static string IncomeStatment {
            get {
                return ResourceManager.GetString("IncomeStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have permetion to Insert.
        /// </summary>
        public static string InsertUnAuth {
            get {
                return ResourceManager.GetString("InsertUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string InvHeader {
            get {
                return ResourceManager.GetString("InvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: All journals With this Invoice Will Be Deleted.
        /// </summary>
        public static string InvoiceDelNote {
            get {
                return ResourceManager.GetString("InvoiceDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNum {
            get {
                return ResourceManager.GetString("InvoiceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices And Receipts.
        /// </summary>
        public static string InvoicesAndReceipts {
            get {
                return ResourceManager.GetString("InvoicesAndReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Due Soon.
        /// </summary>
        public static string InvoicesDueSoon {
            get {
                return ResourceManager.GetString("InvoicesDueSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Num, Product, Client Name.
        /// </summary>
        public static string InvoiceSearchHint {
            get {
                return ResourceManager.GetString("InvoiceSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Reminder Days.
        /// </summary>
        public static string InvoicesReminderDays {
            get {
                return ResourceManager.GetString("InvoicesReminderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paid.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want Schedule Backup?.
        /// </summary>
        public static string IsScheduleBackup {
            get {
                return ResourceManager.GetString("IsScheduleBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Count.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string JHeader {
            get {
                return ResourceManager.GetString("JHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        public static string Journals {
            get {
                return ResourceManager.GetString("Journals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Num or Details.
        /// </summary>
        public static string JournalSearchHint {
            get {
                return ResourceManager.GetString("JournalSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName *.
        /// </summary>
        public static string LastNameReq {
            get {
                return ResourceManager.GetString("LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        public static string Liabilities {
            get {
                return ResourceManager.GetString("Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities Total.
        /// </summary>
        public static string LiabilitiesTotal {
            get {
                return ResourceManager.GetString("LiabilitiesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineNum.
        /// </summary>
        public static string LineNum {
            get {
                return ResourceManager.GetString("LineNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litters Must be less than.
        /// </summary>
        public static string LittersTooLong {
            get {
                return ResourceManager.GetString("LittersTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moblie Internet.
        /// </summary>
        public static string MoblieInternet {
            get {
                return ResourceManager.GetString("MoblieInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        public static string Multiplier {
            get {
                return ResourceManager.GetString("Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Chose An Account!.
        /// </summary>
        public static string MustChoseAccount {
            get {
                return ResourceManager.GetString("MustChoseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Pay Total Price!.
        /// </summary>
        public static string MustPayTotalPrice {
            get {
                return ResourceManager.GetString("MustPayTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name is exist!!.
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        public static string NameReq {
            get {
                return ResourceManager.GetString("NameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Equity.
        /// </summary>
        public static string NetEquity {
            get {
                return ResourceManager.GetString("NetEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Fiscal Year.
        /// </summary>
        public static string NewFiscalYear {
            get {
                return ResourceManager.GetString("NewFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Movement.
        /// </summary>
        public static string NoMovement {
            get {
                return ResourceManager.GetString("NoMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permetion Error!.
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num is exist!!.
        /// </summary>
        public static string NumExist {
            get {
                return ResourceManager.GetString("NumExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Num &gt; 0.
        /// </summary>
        public static string NumIs0 {
            get {
                return ResourceManager.GetString("NumIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numric Only.
        /// </summary>
        public static string NumOnly {
            get {
                return ResourceManager.GetString("NumOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num *.
        /// </summary>
        public static string NumReq {
            get {
                return ResourceManager.GetString("NumReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Is Too Long.
        /// </summary>
        public static string NumTooLong {
            get {
                return ResourceManager.GetString("NumTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Of Open Balance Capital Account Must Be Equal 0.
        /// </summary>
        public static string OpenBalance {
            get {
                return ResourceManager.GetString("OpenBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string OpeningBalance {
            get {
                return ResourceManager.GetString("OpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwrod.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        public static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pay.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Receipt.
        /// </summary>
        public static string PayReceipt {
            get {
                return ResourceManager.GetString("PayReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayReceipts.
        /// </summary>
        public static string PayReceipts {
            get {
                return ResourceManager.GetString("PayReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pays.
        /// </summary>
        public static string pays {
            get {
                return ResourceManager.GetString("pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage *.
        /// </summary>
        public static string PercentageReq {
            get {
                return ResourceManager.GetString("PercentageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 to 100.
        /// </summary>
        public static string PercentOnly {
            get {
                return ResourceManager.GetString("PercentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone *.
        /// </summary>
        public static string PhoneReq {
            get {
                return ResourceManager.GetString("PhoneReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Buy.
        /// </summary>
        public static string PriceBuy {
            get {
                return ResourceManager.GetString("PriceBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Sale.
        /// </summary>
        public static string PriceSale {
            get {
                return ResourceManager.GetString("PriceSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have permetion to Print.
        /// </summary>
        public static string PrintUnAuth {
            get {
                return ResourceManager.GetString("PrintUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If there is Invoices with this Product you will must delete them frist...
        /// </summary>
        public static string ProductDelNote {
            get {
                return ResourceManager.GetString("ProductDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code or Name.
        /// </summary>
        public static string ProductSearchHint {
            get {
                return ResourceManager.GetString("ProductSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductTranactions.
        /// </summary>
        public static string ProductTrans {
            get {
                return ResourceManager.GetString("ProductTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit And Loss.
        /// </summary>
        public static string ProfitLoss {
            get {
                return ResourceManager.GetString("ProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return.
        /// </summary>
        public static string PurchaseReturn {
            get {
                return ResourceManager.GetString("PurchaseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases Invoices.
        /// </summary>
        public static string PurchasesInvoices {
            get {
                return ResourceManager.GetString("PurchasesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases Returns.
        /// </summary>
        public static string PurchasesReturns {
            get {
                return ResourceManager.GetString("PurchasesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases Returns Invoices.
        /// </summary>
        public static string PurchasesReturnsInvoices {
            get {
                return ResourceManager.GetString("PurchasesReturnsInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: All journals With this Receipt Will Be Deleted.
        /// </summary>
        public static string ReceiptDelNote {
            get {
                return ResourceManager.GetString("ReceiptDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Num.
        /// </summary>
        public static string ReceiptNum {
            get {
                return ResourceManager.GetString("ReceiptNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Num, Account Name.
        /// </summary>
        public static string ReceiptSearchHint {
            get {
                return ResourceManager.GetString("ReceiptSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string RecHeader {
            get {
                return ResourceManager.GetString("RecHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Now.
        /// </summary>
        public static string RestoreNow {
            get {
                return ResourceManager.GetString("RestoreNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenues.
        /// </summary>
        public static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Invoices.
        /// </summary>
        public static string ReviewInvoices {
            get {
                return ResourceManager.GetString("ReviewInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Receitpt.
        /// </summary>
        public static string ReviewReceitpt {
            get {
                return ResourceManager.GetString("ReviewReceitpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role *.
        /// </summary>
        public static string RoleReq {
            get {
                return ResourceManager.GetString("RoleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Return.
        /// </summary>
        public static string SaleReturn {
            get {
                return ResourceManager.GetString("SaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoices.
        /// </summary>
        public static string SalesInvoices {
            get {
                return ResourceManager.GetString("SalesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Returns.
        /// </summary>
        public static string SalesReturns {
            get {
                return ResourceManager.GetString("SalesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Returns Invoices.
        /// </summary>
        public static string SalesReturnsInvoices {
            get {
                return ResourceManager.GetString("SalesReturnsInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Print.
        /// </summary>
        public static string SavePrint {
            get {
                return ResourceManager.GetString("SavePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have permetion to View.
        /// </summary>
        public static string SelectUnAuth {
            get {
                return ResourceManager.GetString("SelectUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingExpenses.
        /// </summary>
        public static string ShippingExpenses {
            get {
                return ResourceManager.GetString("ShippingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signutre/.
        /// </summary>
        public static string Signutre {
            get {
                return ResourceManager.GetString("Signutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Must Be Befor End Date!.
        /// </summary>
        public static string StartDateBiger {
            get {
                return ResourceManager.GetString("StartDateBiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statment Equity.
        /// </summary>
        public static string StatmentEquity {
            get {
                return ResourceManager.GetString("StatmentEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Not Active.
        /// </summary>
        public static string StatusNotActive {
            get {
                return ResourceManager.GetString("StatusNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status *.
        /// </summary>
        public static string StatusReq {
            get {
                return ResourceManager.GetString("StatusReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If there is product`s Categories with this Store you will must delete them frist...
        /// </summary>
        public static string StoreDelNote {
            get {
                return ResourceManager.GetString("StoreDelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Info.
        /// </summary>
        public static string StoreInfo {
            get {
                return ResourceManager.GetString("StoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store *.
        /// </summary>
        public static string StoreReq {
            get {
                return ResourceManager.GetString("StoreReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successfully..
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Message..
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Process..
        /// </summary>
        public static string SuccessProcess {
            get {
                return ResourceManager.GetString("SuccessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Action.
        /// </summary>
        public static string TaskAction {
            get {
                return ResourceManager.GetString("TaskAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent *.
        /// </summary>
        public static string TaxPercentReq {
            get {
                return ResourceManager.GetString("TaxPercentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account.
        /// </summary>
        public static string TheAccount {
            get {
                return ResourceManager.GetString("TheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bank.
        /// </summary>
        public static string TheBank {
            get {
                return ResourceManager.GetString("TheBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category.
        /// </summary>
        public static string TheCategory {
            get {
                return ResourceManager.GetString("TheCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Client.
        /// </summary>
        public static string TheClient {
            get {
                return ResourceManager.GetString("TheClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Invoice.
        /// </summary>
        public static string TheInvoice {
            get {
                return ResourceManager.GetString("TheInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheJournal.
        /// </summary>
        public static string TheJournal {
            get {
                return ResourceManager.GetString("TheJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheProduct.
        /// </summary>
        public static string TheProduct {
            get {
                return ResourceManager.GetString("TheProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Receipt.
        /// </summary>
        public static string TheReceipt {
            get {
                return ResourceManager.GetString("TheReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Role.
        /// </summary>
        public static string TheRole {
            get {
                return ResourceManager.GetString("TheRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Store.
        /// </summary>
        public static string TheStore {
            get {
                return ResourceManager.GetString("TheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string ToAccount {
            get {
                return ResourceManager.GetString("ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Client.
        /// </summary>
        public static string ToClient {
            get {
                return ResourceManager.GetString("ToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total QTY.
        /// </summary>
        public static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Balance.
        /// </summary>
        public static string TransferredBalance {
            get {
                return ResourceManager.GetString("TransferredBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Expenses.
        /// </summary>
        public static string TransportationExpenses {
            get {
                return ResourceManager.GetString("TransportationExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Blance.
        /// </summary>
        public static string TrialBlance {
            get {
                return ResourceManager.GetString("TrialBlance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type *.
        /// </summary>
        public static string TypeReq {
            get {
                return ResourceManager.GetString("TypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Update.
        /// </summary>
        public static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have permetion to Update.
        /// </summary>
        public static string UpdateUnAuth {
            get {
                return ResourceManager.GetString("UpdateUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Exist.
        /// </summary>
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName *.
        /// </summary>
        public static string UserNameReq {
            get {
                return ResourceManager.GetString("UserNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa *.
        /// </summary>
        public static string VisaReq {
            get {
                return ResourceManager.GetString("VisaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visas.
        /// </summary>
        public static string Visas {
            get {
                return ResourceManager.GetString("Visas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email Or Pass.
        /// </summary>
        public static string WrongEmailOrPass {
            get {
                return ResourceManager.GetString("WrongEmailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
