//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Img { get; set; }
        public string LocalImg { get; set; }
        public byte ClinetTypeId { get; set; }
        public bool IsCompany { get; set; }
        public bool StatusN { get; set; }
        public System.Guid AccountId { get; set; }
        public string LocalImage { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ClientType ClientType { get; set; }
    }
}
