//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public System.Guid EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpPhone { get; set; }
        public string EmpAddress { get; set; }
        public string EmpImage { get; set; }
        public Nullable<decimal> EmpSal { get; set; }
        public Nullable<System.DateTime> EmpHireDate { get; set; }
        public string EmpComm { get; set; }
        public bool StatusN { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SecUser SecUser { get; set; }
    }
}
