//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public System.Guid Id { get; set; }
        public int QTY { get; set; }
        public decimal Price { get; set; }
        public string Notes { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.Guid ProductUnitId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
