//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.JournalDets = new HashSet<JournalDet>();
        }
    
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
        public byte JournalTypeId { get; set; }
        public Nullable<System.Guid> RefId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDet> JournalDets { get; set; }
        public virtual JournalType JournalType { get; set; }
        public virtual SecUser SecUser { get; set; }
    }
}
