//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDet
    {
        public System.Guid Id { get; set; }
        public decimal Credit { get; set; }
        public decimal Debt { get; set; }
        public string Note { get; set; }
        public System.Guid JournalId { get; set; }
        public System.Guid AccountID { get; set; }
        public int Num { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
