//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CropAccountingAppEntities : DbContext
    {
        public CropAccountingAppEntities(string con = "name=CropAccountingAppEntities")
            : base("name=CropAccountingAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountEnd> AccountEnds { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<CorpBank> CorpBanks { get; set; }
        public virtual DbSet<CorpInfo> CorpInfoes { get; set; }
        public virtual DbSet<CorpType> CorpTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CropStatu> CropStatus { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<FiscalYear> FiscalYears { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<JournalDet> JournalDets { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<JournalType> JournalTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductUnit> ProductUnits { get; set; }
        public virtual DbSet<ReceiptInvoice> ReceiptInvoices { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptType> ReceiptTypes { get; set; }
        public virtual DbSet<SecActionType> SecActionTypes { get; set; }
        public virtual DbSet<SecLocalRole> SecLocalRoles { get; set; }
        public virtual DbSet<SecLocalRoleTask> SecLocalRoleTasks { get; set; }
        public virtual DbSet<SecMasterTask> SecMasterTasks { get; set; }
        public virtual DbSet<SecRole> SecRoles { get; set; }
        public virtual DbSet<SecRoleTask> SecRoleTasks { get; set; }
        public virtual DbSet<SecTask> SecTasks { get; set; }
        public virtual DbSet<SecUser> SecUsers { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UnitConversion> UnitConversions { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserStatus> UserStatuses { get; set; }
        public virtual DbSet<Visa> Visas { get; set; }
        public virtual DbSet<SecUserTrack> SecUserTracks { get; set; }
    }
}
