//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecTask()
        {
            this.SecLocalRoleTasks = new HashSet<SecLocalRoleTask>();
            this.SecRoleTasks = new HashSet<SecRoleTask>();
        }
    
        public short Id { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<short> TOrder { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> cSelect { get; set; }
        public Nullable<bool> cInsert { get; set; }
        public Nullable<bool> cUpdate { get; set; }
        public Nullable<bool> cDelete { get; set; }
        public Nullable<bool> cPrint { get; set; }
        public Nullable<byte> MasterTaskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecLocalRoleTask> SecLocalRoleTasks { get; set; }
        public virtual SecMasterTask SecMasterTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecRoleTask> SecRoleTasks { get; set; }
    }
}
