//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecUserTrack
    {
        public System.Guid UserId { get; set; }
        public short TaskId { get; set; }
        public byte ActionId { get; set; }
        public Nullable<long> TrackDate { get; set; }
    }
}
