//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public System.Guid CorpBankId { get; set; }
    
        public virtual CorpBank CorpBank { get; set; }
    }
}
